version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - '5432:5432'
    volumes:
      - katana-db:/var/lib/postgresql/data

  katana:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - '3000:3000'
        
volumes:
  katana-db: